### ISSUE TITLE
how can I use it?

### ISSUE THREAD

**Issue by farvardin** [EdouardBERGE/wav2ay#1]
Hello, 

I've compiled it, and managed to convert a wav to an other wav with a CPC sound.

But how can I use the dumped data to create an .ay file, or a binary file for the cpc, like in your example?

**Comment by EdouardBERGE** [comment]
the output is a list of values for AY registers, you have to write your own code

the example use DMA list output because it's the easiest way to replay samples at any frequency

on regular CPC (i mean not Amstrad Plus) you have to write a simple player and the synchronisation part

the tool is not supposed to be used for "fun", it's for advanced coder (except with WAV output as preview)

**Comment by EdouardBERGE** [comment]
with initialised Asic, you can replay DMA list with code like this

```
megaloop

;******************************
;***** LAUNCH DMA LIST ********
;******************************
ld hl,sample
ld (#6C04),hl
ld hl,#6C06
ld (hl),0 ; Minimum value for PAUSE register
ld hl,#6C0F
ld (hl),%10 ; DMA 1

ld hl,50*8 ; wait 8 seconds
ld b,#F5
.novbl in a,(c) : rra : jr c,.novbl
.vbl in a,(c) : rra : jr nc,.vbl
ld a,e
ld (#6400),a

dec hl
ld a,h
or l
jr nz,.novbl

jr megaloop ; play again each 8s

align 2
sample
defw #0700+%111000 ; ALL channels ON
defw 0,8,0,9,0,10  ; ALL volumes to ZERO
include 'sample.dma' ; generated DMA list <= YOU FILE HERE !!!
defw #0700+%111111 ; channel OFF
defw #4020         ; END of DMA list

```

**Comment by EdouardBERGE** [comment]
source code example for Plus and CPC
